In [1]:
import pandas as pd

In [2]:
#Importing Data from the city of Chicago Website
chicago_uncleaned = pd.read_csv('Chicago Crimes.csv')

C:\Users\bsnus\.conda\envs\Decision Tree\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
#Dropping Null Values
chicago_uncleaned.dropna()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
60282,11556037,JC103643,01/03/2019 07:20:00 PM,0000X W RWY 27R,2890,PUBLIC PEACE VIOLATION,OTHER VIOLATION,AIRCRAFT,False,False,...,41.0,76.0,26,1100374.0,1943906.0,2019,08/17/2019 03:57:45 PM,42.002816,-87.906094,"(42.002816387, -87.90609433)"
62200,11626027,JC188126,03/16/2019 05:58:00 PM,001XX N WELLS ST,0460,BATTERY,SIMPLE,STREET,False,False,...,42.0,32.0,08B,1174723.0,1900866.0,2019,08/17/2019 03:57:45 PM,41.883369,-87.633860,"(41.88336939, -87.633860272)"
62540,11622422,JC183696,03/12/2019 10:00:00 PM,008XX E 38TH PL,0820,THEFT,$500 AND UNDER,RESIDENTIAL YARD (FRONT/BACK),False,False,...,4.0,36.0,06,1182276.0,1879784.0,2019,08/17/2019 03:57:45 PM,41.825347,-87.606781,"(41.825346902, -87.606780575)"
62572,11625922,JC185669,03/14/2019 06:42:00 PM,074XX N PAULINA ST,0460,BATTERY,SIMPLE,RESIDENCE,False,False,...,49.0,1.0,08B,1163827.0,1949311.0,2019,08/17/2019 03:57:45 PM,42.016542,-87.672499,"(42.016541612, -87.672499325)"
62573,11622907,JC185406,03/14/2019 04:03:00 PM,008XX E 38TH PL,5002,OTHER OFFENSE,OTHER VEHICLE OFFENSE,STREET,False,True,...,4.0,36.0,26,1182227.0,1879766.0,2019,08/17/2019 03:57:45 PM,41.825299,-87.606961,"(41.825298645, -87.6069609)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7197790,9999998,HY188874,03/18/2015 04:00:00 AM,036XX W BELMONT AVE,0460,BATTERY,SIMPLE,RESIDENCE,False,False,...,35.0,21.0,08B,1151659.0,1921038.0,2015,02/10/2018 03:50:01 PM,41.939208,-87.718022,"(41.939207846, -87.718021657)"
7197791,9999999,HY189683,03/18/2015 05:08:00 PM,043XX N CENTRAL AVE,0560,ASSAULT,SIMPLE,RESTAURANT,True,False,...,38.0,15.0,08A,1138222.0,1928502.0,2015,02/10/2018 03:50:01 PM,41.959944,-87.767226,"(41.959943835, -87.767225719)"
7197793,11700926,JC279725,05/26/2019 05:13:00 PM,036XX W DOUGLAS BLVD,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,APARTMENT,False,True,...,24.0,29.0,26,1152126.0,1893208.0,2019,06/30/2019 03:56:27 PM,41.862830,-87.717040,"(41.862830429, -87.717040084)"
7197794,24560,JC279072,05/26/2019 06:48:00 AM,013XX W HASTINGS ST,0110,HOMICIDE,FIRST DEGREE MURDER,CHA PARKING LOT,True,False,...,25.0,28.0,01A,1167752.0,1893853.0,2019,06/20/2020 03:48:45 PM,41.864278,-87.659660,"(41.864278228, -87.659660218)"
7197797,24559,JC278908,05/26/2019 02:11:00 AM,013XX W HASTINGS ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,25.0,28.0,01A,1167746.0,1893853.0,2019,06/20/2020 03:48:45 PM,41.864278,-87.659682,"(41.864278357, -87.659682244)"

In [4]:
# I am just going to filter the data from the last decade. There is a ton of data in here and I will just filter this from 2010 to 2019. 
chicago = chicago_uncleaned[(chicago_uncleaned['Year'] >= 2010) & (chicago_uncleaned['Year'] <= 2019)]

In [5]:
chicago.head(10)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
1,11227287,JB147188,10/08/2017 03:00:00 AM,092XX S RACINE AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,False,False,...,21.0,73.0,02,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
2,11227583,JB147595,03/28/2017 02:00:00 PM,026XX W 79TH ST,0620,BURGLARY,UNLAWFUL ENTRY,OTHER,False,False,...,18.0,70.0,05,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
3,11227293,JB147230,09/09/2017 08:17:00 PM,060XX S EBERHART AVE,0810,THEFT,OVER $500,RESIDENCE,False,False,...,20.0,42.0,06,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
4,11227634,JB147599,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,42.0,32.0,02,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
5,11227503,JB146383,01/01/2015 12:01:00 AM,061XX S KILBOURN AVE,1751,OFFENSE INVOLVING CHILDREN,CRIM SEX ABUSE BY FAM MEMBER,RESIDENCE,False,True,...,13.0,65.0,17,NaN,NaN,2015,04/12/2019 04:00:15 PM,NaN,NaN,NaN
6,11227508,JB146365,01/01/2017 12:01:00 AM,027XX S WHIPPLE ST,1754,OFFENSE INVOLVING CHILDREN,AGG SEX ASSLT OF CHILD FAM MBR,RESIDENCE,False,False,...,12.0,30.0,02,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
7,11022695,JA353568,07/17/2017 10:10:00 AM,021XX W MC LEAN AVE,0810,THEFT,OVER $500,RESIDENCE,False,False,...,32.0,22.0,06,NaN,NaN,2017,07/24/2017 03:54:23 PM,NaN,NaN,NaN
8,11227633,JB147500,12/28/2017 03:55:00 PM,011XX S MICHIGAN AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,2.0,32.0,11,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
9,11227586,JB147613,02/10/2017 12:00:00 PM,089XX S COTTAGE GROVE AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,...,8.0,44.0,14,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
10,11227475,JB147314,11/22/2017 02:42:00 AM,056XX N CHRISTIANA AVE,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,APARTMENT,False,True,...,39.0,13.0,26,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN

In [6]:
#Importing Necessary Packages
import seaborn as sns
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import scipy as sp 
import matplotlib.cm as cm
%matplotlib inline

In [7]:
#Dropping Unnecessary Columns
chicago = chicago.drop(['Case Number', 'Domestic', 'Beat', 'Updated On', 'Arrest'], 1)

In [8]:
#Grouping the most common Crimes
chicago_crime = chicago.groupby('Primary Type')['Primary Type'].count()
chicago_crime.sort_values(ascending = False, inplace = True)
chicago_crime.head(50)

Primary Type
THEFT                                671483
BATTERY                              536199
CRIMINAL DAMAGE                      315730
NARCOTICS                            258129
ASSAULT                              192828
OTHER OFFENSE                        180763
BURGLARY                             170195
DECEPTIVE PRACTICE                   161609
MOTOR VEHICLE THEFT                  129103
ROBBERY                              114508
CRIMINAL TRESPASS                     75198
WEAPONS VIOLATION                     41143
PUBLIC PEACE VIOLATION                24096
OFFENSE INVOLVING CHILDREN            23687
PROSTITUTION                          14646
CRIM SEXUAL ASSAULT                   13898
INTERFERENCE WITH PUBLIC OFFICER      11936
SEX OFFENSE                           10819
HOMICIDE                               5314
ARSON                                  4419
GAMBLING                               4409
LIQUOR LAW VIOLATION                   4000
KIDNAPPING                             2202
STALKING                               1823
INTIMIDATION                           1516
CRIMINAL SEXUAL ASSAULT                 990
CONCEALED CARRY LICENSE VIOLATION       520
OBSCENITY                               494
NON-CRIMINAL                            170
PUBLIC INDECENCY                        116
HUMAN TRAFFICKING                        64
OTHER NARCOTIC VIOLATION                 61
NON - CRIMINAL                           38
NON-CRIMINAL (SUBJECT SPECIFIED)          9
Name: Primary Type, dtype: int64

We can see the most common crimes are Theft, Battery, and Criminal Damage.

In [9]:
crime_list = chicago_crime.index.values[0:25].tolist()
chicago = chicago[chicago['Primary Type'].isin(crime_list)]

In [10]:
#Anything that is not Primary type is listed as 'other offense'.
chicago = chicago[chicago['Primary Type']!= 'OTHER OFFENSE']

In [11]:
#Listed what I considered a Serious Crime
serious_crimes = ['ARSON', 'ASSAULT', 'BATTERY', 'CRIM SEXUAL ASSAULT', 'CRIMINAL DAMAGE', 'CRIMINAL TRESPASS', 'HOMICIDE', 'ROBBERY']
chicago['serious']=np.where(chicago['Primary Type'].isin(serious_crimes), 1, 0)
chicago.head(10)

,ID,Date,Block,IUCR,Primary Type,Description,Location Description,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,serious
1,11227287,10/08/2017 03:00:00 AM,092XX S RACINE AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,22.0,21.0,73.0,02,NaN,NaN,2017,NaN,NaN,NaN,1
2,11227583,03/28/2017 02:00:00 PM,026XX W 79TH ST,0620,BURGLARY,UNLAWFUL ENTRY,OTHER,8.0,18.0,70.0,05,NaN,NaN,2017,NaN,NaN,NaN,0
3,11227293,09/09/2017 08:17:00 PM,060XX S EBERHART AVE,0810,THEFT,OVER $500,RESIDENCE,3.0,20.0,42.0,06,NaN,NaN,2017,NaN,NaN,NaN,0
4,11227634,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,1.0,42.0,32.0,02,NaN,NaN,2017,NaN,NaN,NaN,1
5,11227503,01/01/2015 12:01:00 AM,061XX S KILBOURN AVE,1751,OFFENSE INVOLVING CHILDREN,CRIM SEX ABUSE BY FAM MEMBER,RESIDENCE,8.0,13.0,65.0,17,NaN,NaN,2015,NaN,NaN,NaN,0
6,11227508,01/01/2017 12:01:00 AM,027XX S WHIPPLE ST,1754,OFFENSE INVOLVING CHILDREN,AGG SEX ASSLT OF CHILD FAM MBR,RESIDENCE,10.0,12.0,30.0,02,NaN,NaN,2017,NaN,NaN,NaN,0
7,11022695,07/17/2017 10:10:00 AM,021XX W MC LEAN AVE,0810,THEFT,OVER $500,RESIDENCE,14.0,32.0,22.0,06,NaN,NaN,2017,NaN,NaN,NaN,0
8,11227633,12/28/2017 03:55:00 PM,011XX S MICHIGAN AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,1.0,2.0,32.0,11,NaN,NaN,2017,NaN,NaN,NaN,0
9,11227586,02/10/2017 12:00:00 PM,089XX S COTTAGE GROVE AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,6.0,8.0,44.0,14,NaN,NaN,2017,NaN,NaN,NaN,1
11,11227247,01/01/2012 09:00:00 AM,105XX S INDIANAPOLIS AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,4.0,10.0,52.0,11,NaN,NaN,2012,NaN,NaN,NaN,0

In [12]:
print(len(chicago.groupby('Location Description')['Location Description'].count().index.values))

193

In [13]:
#Grouping by location of crime
chicago_crime_location = chicago.groupby('Location Description')['Location Description'].count()
chicago_crime_location.sort_values(ascending=False, inplace = True)
chicago_crime_location.head(50)

Location Description
STREET                               649649
RESIDENCE                            413984
APARTMENT                            343564
SIDEWALK                             301142
OTHER                                100826
PARKING LOT/GARAGE(NON.RESID.)        84168
ALLEY                                 61664
SMALL RETAIL STORE                    59812
RESIDENTIAL YARD (FRONT/BACK)         57489
RESTAURANT                            55387
RESIDENCE-GARAGE                      51111
RESIDENCE PORCH/HALLWAY               50481
VEHICLE NON-COMMERCIAL                49454
SCHOOL, PUBLIC, BUILDING              49128
DEPARTMENT STORE                      43108
GROCERY FOOD STORE                    33263
GAS STATION                           32410
PARK PROPERTY                         23063
BAR OR TAVERN                         20276
CTA TRAIN                             16178
COMMERCIAL / BUSINESS OFFICE          14931
CONVENIENCE STORE                     14238
CTA PLATFORM                          14225
SCHOOL, PUBLIC, GROUNDS               12765
HOTEL/MOTEL                           12675
VACANT LOT/LAND                       11869
CTA BUS                               11505
DRUG STORE                            11112
BANK                                  11002
HOSPITAL BUILDING/GROUNDS              9968
POLICE FACILITY/VEH PARKING LOT        8178
CHA APARTMENT                          7962
CHA PARKING LOT/GROUNDS                7847
DRIVEWAY - RESIDENTIAL                 7336
CTA BUS STOP                           6500
ABANDONED BUILDING                     6481
NURSING HOME/RETIREMENT HOME           6447
CHURCH/SYNAGOGUE/PLACE OF WORSHIP      6245
TAVERN/LIQUOR STORE                    6135
SCHOOL, PRIVATE, BUILDING              5921
CTA GARAGE / OTHER PROPERTY            5477
GOVERNMENT BUILDING/PROPERTY           5461
ATM (AUTOMATIC TELLER MACHINE)         5364
ATHLETIC CLUB                          5184
CTA STATION                            5147
CURRENCY EXCHANGE                      4375
TAXICAB                                4036
CONSTRUCTION SITE                      3567
WAREHOUSE                              3200
SPORTS ARENA/STADIUM                   2931
Name: Location Description, dtype: int64

The most common places where a crime happens in Chicago is on the street, residence, or an apartment.

In [14]:
chicago_location_list = chicago_crime_location.index.values[0:25].tolist()
chicago = chicago[chicago['Location Description'].isin(chicago_location_list)]
chicago.shape

(2564991, 18)

In [15]:
#Adding a D to the district to make things look a little nicer. 
chicago['District']='D' + chicago['District'].astype(str)
chicago.head()

,ID,Date,Block,IUCR,Primary Type,Description,Location Description,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,serious
1,11227287,10/08/2017 03:00:00 AM,092XX S RACINE AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,D22.0,21.0,73.0,02,NaN,NaN,2017,NaN,NaN,NaN,1
2,11227583,03/28/2017 02:00:00 PM,026XX W 79TH ST,0620,BURGLARY,UNLAWFUL ENTRY,OTHER,D8.0,18.0,70.0,05,NaN,NaN,2017,NaN,NaN,NaN,0
3,11227293,09/09/2017 08:17:00 PM,060XX S EBERHART AVE,0810,THEFT,OVER $500,RESIDENCE,D3.0,20.0,42.0,06,NaN,NaN,2017,NaN,NaN,NaN,0
4,11227634,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,D1.0,42.0,32.0,02,NaN,NaN,2017,NaN,NaN,NaN,1
5,11227503,01/01/2015 12:01:00 AM,061XX S KILBOURN AVE,1751,OFFENSE INVOLVING CHILDREN,CRIM SEX ABUSE BY FAM MEMBER,RESIDENCE,D8.0,13.0,65.0,17,NaN,NaN,2015,NaN,NaN,NaN,0

In [16]:
#Adding all the districts to the dataset as columns
chicagodummy=pd.get_dummies(chicago,columns=['Primary Type', 'District'])
chicagodummy=chicagodummy.join(chicago[['Primary Type', 'District']])
print(chicagodummy.shape)
chicagodummy.head()

(2564991, 66)

,ID,Date,Block,IUCR,Description,Location Description,Ward,Community Area,FBI Code,X Coordinate,...,District_D31.0,District_D4.0,District_D5.0,District_D6.0,District_D7.0,District_D8.0,District_D9.0,District_Dnan,Primary Type,District
1,11227287,10/08/2017 03:00:00 AM,092XX S RACINE AVE,0281,NON-AGGRAVATED,RESIDENCE,21.0,73.0,02,NaN,...,0,0,0,0,0,0,0,0,CRIM SEXUAL ASSAULT,D22.0
2,11227583,03/28/2017 02:00:00 PM,026XX W 79TH ST,0620,UNLAWFUL ENTRY,OTHER,18.0,70.0,05,NaN,...,0,0,0,0,0,1,0,0,BURGLARY,D8.0
3,11227293,09/09/2017 08:17:00 PM,060XX S EBERHART AVE,0810,OVER $500,RESIDENCE,20.0,42.0,06,NaN,...,0,0,0,0,0,0,0,0,THEFT,D3.0
4,11227634,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,NON-AGGRAVATED,HOTEL/MOTEL,42.0,32.0,02,NaN,...,0,0,0,0,0,0,0,0,CRIM SEXUAL ASSAULT,D1.0
5,11227503,01/01/2015 12:01:00 AM,061XX S KILBOURN AVE,1751,CRIM SEX ABUSE BY FAM MEMBER,RESIDENCE,13.0,65.0,17,NaN,...,0,0,0,0,0,1,0,0,OFFENSE INVOLVING CHILDREN,D8.0

In [17]:
chicagotimedata=chicagodummy.copy()

In [18]:
from datetime import datetime
format = '%m/%d/%Y %I:%M:%S %p'

In [19]:
#Adding columns to when a crime might have happened
chicagodummy['24hour_time']=chicagodummy.Date.apply(lambda row: datetime.strptime(row, format).strftime('%H:%M'))
chicagodummy['Timeblock']=chicagodummy.Date.apply(lambda row: str(3*int(int(datetime.strptime(row, format).strftime('%H'))/3)))
chicagodummy['Date_no_time']=chicagodummy.Date.apply(lambda row: datetime.strptime(row, format).strftime('%Y%m%d'))
chicagodummy['Weekday']=chicagodummy.Date.apply(lambda row: datetime.strptime(row, format).strftime('%A'))
chicagodummy=pd.get_dummies(chicagodummy, columns = ['Timeblock', 'Weekday'])
chicagodummy.shape

(2564991, 83)

In [20]:
chicago=chicagodummy

In [21]:
chicago = chicago.dropna()
chicago.shape

(2547431, 83)

In [22]:
#Importing all the police station districts that can be found on the city of Chicago Website
chicago_police_stations = pd.read_csv('Police_Stations.csv')

In [23]:
chicago_police_stations.head(10)

      DISTRICT   LATITUDE  LONGITUDE                         LOCATION
0   District 1  41.858373 -87.627356   (41.8583725929, -87.627356171)
1  District 10  41.856685 -87.708382   (41.8566845327, -87.708381958)
2  District 11  41.873582 -87.705488   (41.8735822883, -87.705488126)
3  District 12  41.862977 -87.656973  (41.8629766244, -87.6569725149)
4  District 14  41.921103 -87.697452  (41.9211033246, -87.6974518223)
5  District 15  41.880083 -87.768200   (41.8800834614, -87.768199889)
6  District 16  41.974094 -87.766149  (41.9740944511, -87.7661488432)
7  District 17  41.966053 -87.728115   (41.9660534171, -87.728114561)
8  District 18  41.903242 -87.643352  (41.9032416531, -87.6433521393)
9  District 19  41.947400 -87.651512   (41.9474004564, -87.651512018)

In [24]:
chicago_latitude = np.array(chicago['Latitude'])

In [25]:
chicago_longitude = np.array(chicago['Longitude'])

In [26]:
chicago_latitude_long = zip(chicago_latitude, chicago_longitude)

In [27]:
chicago_latitude_long_list = list(chicago_latitude_long)

In [28]:
chicago_latitude_long_list

[(41.88336939, -87.633860272),
 (41.825346902, -87.606780575),
 (42.016541612, -87.672499325),
 (41.976370778, -87.800502515),
 (41.875590103, -87.633515501),
 (41.917336159, -87.712375085),
 (41.924839894, -87.69405765),
 (41.75702248, -87.558073456),
 (41.884865037, -87.755230327),
 (41.862218265, -87.639087164),
 (41.961449077, -87.777058774),
 (41.857746163, -87.639711853),
 (41.745303445, -87.60016439799999),
 (41.932222582, -87.683432779),
 (41.976490526, -87.791494995),
 (41.884925408, -87.711120923),
 (41.742656445, -87.632018466),
 (41.872642689, -87.716306964),
 (41.697609261, -87.613507612),
 (41.911069616999995, -87.68724043899999),
 (41.960532919, -87.76315773700001),
 (41.903894777, -87.63181425100001),
 (41.902910635, -87.69848983600001),
 (41.764779221, -87.676280498),
 (41.833702334, -87.644958276),
 (41.897499466, -87.69313664399999),
 (41.774789128, -87.689625516),
 (41.897596066999995, -87.62321837299999),
 (41.974832155, -87.786680446),
 (41.721028724, -87.59353928899999),
 (41.75645779, -87.565113432),
 (41.781418541, -87.608405955),
 (41.670279025999996, -87.62242080600001),
 (41.863527271, -87.722653917),
 (41.722103131, -87.551068308),
 (41.809519024000004, -87.607384952),
 (41.912046196999995, -87.74592889200001),
 (41.750653534, -87.64337994899999),
 (41.885738286, -87.63576612),
 (41.976183409, -87.668801484),
 (41.747393001, -87.58543860700001),
 (41.852868298000004, -87.63091491),
 (41.771016576, -87.622724617),
 (42.00413735, -87.668128025),
 (41.895939389, -87.75440321),
 (41.925349997, -87.737891589),
 (42.007440916, -87.666161921),
 (41.923284685, -87.698648012),
 (41.896669722, -87.62876022799999),
 (41.769053315, -87.61856733399999),
 (41.696725665, -87.623224459),
 (41.736711088, -87.663087144),
 (41.751423014000004, -87.676816181),
 (41.783380448, -87.77098146799999),
 (41.762184391, -87.58622352299999),
 (41.878557088, -87.748398495),
 (41.72802938, -87.66284035700001),
 (41.688610361, -87.60953671200001),
 (41.796807255, -87.60560675),
 (41.879613461, -87.709266655),
 (41.901679344, -87.7213979),
 (41.792974653, -87.72315172299999),
 (41.799553224, -87.58789475299999),
 (41.73681344, -87.552802376),
 (41.892628411, -87.63115524),
 (41.779012821, -87.664208692),
 (41.903478069, -87.631433102),
 (41.844752355, -87.690704684),
 (41.869752476, -87.639747289),
 (41.781100462, -87.765509056),
 (41.924133516, -87.75437255),
 (41.792950892, -87.690122246),
 (41.838118825, -87.640555028),
 (41.689208485, -87.53769718),
 (41.963649894, -87.71077103299999),
 (41.702110528, -87.563219289),
 (41.868780233, -87.627458476),
 (41.711393621, -87.654944841),
 (41.789204622, -87.70343754299999),
 (41.826069047, -87.62485689399999),
 (41.766491296, -87.684910192),
 (41.823281439, -87.68488784799999),
 (41.814737762, -87.723843947),
 (41.780727412, -87.667886613),
 (41.896608801999996, -87.63315751799999),
 (41.755297327, -87.65265388700001),
 (41.845537889, -87.714820496),
 (41.998048983000004, -87.70935427100001),
 (41.894821547, -87.63213392799999),
 (41.75409183, -87.623061596),
 (41.84451005, -87.639164866),
 (41.883938846999996, -87.68313278299999),
 (41.794589809, -87.62892956),
 (41.903775756, -87.639324074),
 (41.764535195, -87.693334867),
 (41.978160468, -87.689240087),
 (41.898175531, -87.63627725100001),
 (41.809314925, -87.620808615),
 (41.89655687, -87.63680173200001),
 (41.852004263000005, -87.688536253),
 (41.879292799, -87.741484659),
 (41.765965501, -87.680744061),
 (41.796458615, -87.603857722),
 (41.849295816, -87.71859043100001),
 (41.894826355999996, -87.767290594),
 (41.842682383, -87.661784165),
 (41.795652442, -87.619247355),
 (41.88059972, -87.63916731),
 (41.772523095, -87.583841674),
 (41.711408121, -87.64538197600001),
 (41.750066278, -87.554913938),
 (41.891990384, -87.61146150200001),
 (41.978991238, -87.65994197200001),
 (41.877359722, -87.749305368),
 (41.899168384, -87.709164449),
 (41.76487209, -87.61040667399999),
 (41.785751501, -87.687477185),
 (41.73848935, -87.552675826),
 (41.871833434, -87.72666504799999),
 (41.880132758, -87.745266514),
 (41.751270583, -87.60593808200001),
 (41.87683799, -87.703547124),
 (41.74867757, -87.61647372200001),
 (41.947575435, -87.777855781),
 (41.90043594, -87.75415322),
 (41.825123682, -87.61229385),
 (41.749146564, -87.557699157),
 (41.807570583, -87.689301125),
 (41.768069819000004, -87.567306284),
 (41.722373679, -87.661488866),
 (41.69634565, -87.615506296),
 (41.858904921, -87.64484222700001),
 (41.73614279, -87.62909594899999),
 (41.707027472, -87.63435046),
 (42.015393801, -87.67907608600001),
 (41.722461826, -87.651758755),
 (41.764977109, -87.62328610899999),
 (41.742858775, -87.724809994),
 (42.007014318, -87.66500369399999),
 (41.789846121, -87.652336186),
 (41.796808634, -87.668307054),
 (41.774659906, -87.69449901700001),
 (41.805776361, -87.675832432),
 (41.881592273, -87.63675863799999),
 (41.764303086999995, -87.649245116),
 (41.878840427, -87.639582928),
 (41.969140197, -87.724426194),
 (41.805930728, -87.66125114299999),
 (41.744995431, -87.656408769),
 (41.819548845999996, -87.623109131),
 (41.910676312, -87.64918706899999),
 (41.769399886, -87.690705813),
 (41.838706452, -87.72595418),
 (41.896551396, -87.773787663),
 (41.936781716999995, -87.65886094),
 (41.761273685999996, -87.560969185),
 (41.760132634, -87.579232064),
 (41.785256921999995, -87.730279594),
 (41.980220925, -87.775663342),
 (41.810129078, -87.69091880299999),
 (41.875892535, -87.704287105),
 (41.890849559, -87.71251782700001),
 (41.946512428000005, -87.716900113),
 (41.881391643, -87.68643785100001),
 (41.885972518, -87.653314091),
 (41.782293453, -87.600538793),
 (41.981166319, -87.79433883),
 (41.698107353000005, -87.53045450100001),
 (41.901122152, -87.69516117799999),
 (41.939120102, -87.746875019),
 (41.948703283, -87.677453607),
 (41.773766875, -87.64948916799999),
 (41.776216344, -87.704022921),
 (41.85058958, -87.719844334),
 (41.897616218, -87.762094231),
 (41.811247709, -87.66382563200001),
 (41.875066021, -87.741362098),
 (41.877565108, -87.68479102),
 (41.942248935, -87.81300828299999),
 (41.983254654, -87.66870588799999),
 (41.901073698000005, -87.63136393),
 (41.890389116, -87.628021263),
 (41.829389915, -87.60689263399999),
 (41.895558371999996, -87.70589759299999),
 (41.908432264, -87.769514248),
 (41.885373604, -87.74406532299999),
 (41.921529068000005, -87.746231419),
 (41.830109680999996, -87.610058377),
 (41.696711205999996, -87.62800671299999),
 (41.846455266999996, -87.69490466399999),
 (41.904329661999995, -87.667996915),
 (41.788474424, -87.65473049299999),
 (41.859918745, -87.72011125200001),
 (41.905041373, -87.74939479),
 (41.844428053, -87.711557497),
 (41.873204996, -87.658677936),
 (41.727632307, -87.559489294),
 (41.76471549, -87.6334241),
 (41.914092032, -87.717899225),
 (42.005353278, -87.67197125),
 (41.902876025, -87.77417692700001),
 (41.761779227, -87.68928273200001),
 (41.903319631, -87.632900531),
 (41.861642001999996, -87.7299295),
 (41.875580565, -87.71608042700001),
 (41.809687513, -87.674970791),
 (41.793876041, -87.649323127),
 (41.90971226, -87.73926766),
 (41.682468145, -87.659103605),
 (41.756604794, -87.576095781),
 (41.903453426, -87.69442899100001),
 (41.715863801, -87.636998103),
 (41.922138554, -87.697332876),
 (41.78782098, -87.68509131399999),
 (41.870892373000004, -87.71182245600001),
 (41.770007163, -87.69182882),
 (42.020226133, -87.66948762),
 (41.718471269, -87.559818981),
 (41.724505269, -87.619050305),
 (41.784142336, -87.67281955899999),
 (41.844492723, -87.706793137),
 (41.808584003, -87.665881774),
 (41.783007620999996, -87.67211256200001),
 (41.748134926, -87.727706481),
 (41.835915905, -87.66570061),
 (41.778844905999996, -87.710988877),
 (41.867015632, -87.646917628),
 (41.757751768, -87.60537011),
 (41.731778744, -87.636199764),
 (41.745250808, -87.60137791),
 (41.751468669, -87.667107794),
 (41.752950248000005, -87.554061838),
 (41.709577534, -87.65738476),
 (41.913186019, -87.647135902),
 (41.795448721999996, -87.660979271),
 (41.841142759, -87.625215429),
 (41.758315679, -87.567579897),
 (41.847670913, -87.706351061),
 (41.72116399, -87.562350799),
 (41.896888585999996, -87.628203192),
 (41.883093993, -87.679814278),
 (41.773600901, -87.62838573200001),
 (41.754005513, -87.662581071),
 (41.731292661, -87.59656123100001),
 (41.678887433, -87.637118655),
 (41.877004411, -87.62473154899999),
 (41.692833841, -87.60431945),
 (41.655616525999996, -87.61412541700001),
 (41.895941933, -87.74679272200001),
 (41.878476241, -87.774598987),
 (41.700364212, -87.540086344),
 (41.698422453, -87.69640753600001),
 (41.782447056, -87.660642136),
 (41.807867569, -87.65136775100001),
 (41.790752055, -87.625601621),
 (41.799517726, -87.591313255),
 (41.774183794, -87.600924395),
 (41.736656017, -87.563638425),
 (41.707592432, -87.535284185),
 (41.855235085, -87.653929781),
 (41.677322822, -87.62627470700001),
 (41.755923803, -87.65743376),
 (41.706601831, -87.66805462),
 (41.780571936, -87.775259047),
 (41.682761255, -87.63240932),
 (41.72444317, -87.626315136),
 (41.751897254, -87.55377772799999),
 (41.702945165, -87.62070249899999),
 (41.732860795, -87.613627076),
 (41.678949434, -87.62392142200001),
 (41.902611949000004, -87.669924906),
 (41.877470199, -87.67822287700001),
 (41.773273248, -87.592451667),
 (41.779711108, -87.713851263),
 (41.89498119, -87.74889509399999),
 (41.882641471999996, -87.669338326),
 (41.770116488, -87.61698656700001),
 (41.736774091, -87.56242059899999),
 (41.678634792, -87.62052783200001),
 (41.790314426, -87.670944722),
 (41.895729959, -87.624991059),
 (41.891145176, -87.61233778100001),
 (41.763625741999995, -87.56018223299999),
 (41.659120594, -87.63406366299999),
 (41.755381743, -87.56466081399999),
 (41.913116793, -87.75901684700001),
 (41.81110081, -87.70285258700001),
 (41.765804251999995, -87.60982804700001),
 (41.773864414, -87.588808175),
 (41.688181442, -87.61949984799999),
 (41.787208166, -87.634400539),
 (41.982574075, -87.667282235),
 (41.902501122, -87.73675947),
 (41.886446465, -87.615750906),
 (41.879474722, -87.74057598200001),
 (41.875820724, -87.647175913),
 (41.892569818000005, -87.62208039),
 (41.924809614000004, -87.76723509899999),
 (41.749591278000004, -87.55285648899999),
 (41.682369298000005, -87.645204489),
 (41.876650547, -87.755587101),
 (41.797399927, -87.62091494200001),
 (41.850657367, -87.631966812),
 (41.894884155, -87.76123339799999),
 (41.812998842, -87.75154846299999),
 (41.947528473, -87.713967935),
 (41.714488412, -87.564598866),
 (41.859968413000004, -87.72377070799999),
 (41.883198249, -87.73943254),
 (41.885729338000004, -87.625780935),
 (41.75852909, -87.608517015),
 (41.813187768, -87.669949774),
 (41.775378251, -87.645890263),
 (41.807759468, -87.677095939),
 (41.935156334, -87.639384562),
 (41.915971151, -87.746065586),
 (41.771276967, -87.66520556299999),
 (41.902678521, -87.72558336899999),
 (41.967490183, -87.69498826600001),
 (41.729160106, -87.58548161),
 (41.772411293000005, -87.587747195),
 (41.868380637, -87.62584744899999),
 (41.702506364, -87.63145154600001),
 (41.941429217, -87.757417575),
 (41.881536184, -87.637012627),
 (41.908560535, -87.67740914299999),
 (41.7896434, -87.666903347),
 (41.756906454, -87.555523979),
 (41.991306282, -87.688460159),
 (41.886511115, -87.618196037),
 (41.761921826, -87.694178209),
 (41.892509386, -87.626069718),
 (41.736255058000005, -87.62816043299999),
 (41.793924612, -87.67358091700001),
 (41.907926167, -87.64819515),
 (41.853381705, -87.733057386),
 (41.906545818000005, -87.650498565),
 (41.754005513, -87.662581071),
 (41.908668475, -87.627577615),
 (41.772692000999996, -87.626511384),
 (41.874380415, -87.72361542600001),
 (41.797206215, -87.66588249),
 (41.782467577, -87.657125736),
 (41.900926245, -87.754516118),
 (41.75044125, -87.613694591),
 (41.901241115, -87.764809559),
 (41.678038746, -87.621771684),
 (41.868412647, -87.720191625),
 (41.913328391, -87.692184903),
 (41.719012149, -87.66341393799999),
 (41.969159427, -87.649837624),
 (41.726560961, -87.60812913299999),
 (41.919266205, -87.678445911),
 (41.943338611, -87.64332075),
 (41.726560961, -87.60812913299999),
 (41.966053999, -87.657890403),
 (41.750637386, -87.64434760299999),
 (41.846160861, -87.695259926),
 (41.895644675, -87.769072114),
 (41.729926845, -87.649529363),
 (41.748809736999995, -87.60389903299999),
 (41.77073417, -87.60696828399999),
 (41.876747289, -87.74813593399999),
 (41.902346538, -87.629939417),
 (41.80269215, -87.616264407),
 (41.760440542, -87.67341820899999),
 (41.709926798000005, -87.621599589),
 (41.879097968, -87.63228381799999),
 (41.690567503000004, -87.621025854),
 (41.945092059000004, -87.6548145),
 (41.870931735, -87.686157813),
 (41.889243957, -87.628783073),
 (41.679408594, -87.617861659),
 (41.735975176, -87.586893744),
 (41.795299028, -87.66826398399999),
 (41.687924411, -87.63982199899999),
 (41.909325275, -87.769745185),
 (41.890464277, -87.654610654),
 (41.884493832, -87.627021129),
 (41.732214483, -87.62532866299999),
 (41.963629388, -87.652992668),
 (41.809401704, -87.61535327),
 (41.839963581999996, -87.661445613),
 (41.934474646, -87.64421014700001),
 (41.98538955, -87.71382914200001),
 (41.772889498000005, -87.619837161),
 (41.884076765, -87.721723807),
 (41.883608576, -87.707156605),
 (41.931012239, -87.784901193),
 (41.746933449000004, -87.613601845),
 (41.659087388, -87.644929089),
 (41.877848189, -87.736493098),
 (41.776273382, -87.592974394),
 (41.857846705, -87.663115887),
 (41.752686085, -87.59552136299999),
 (41.791344209, -87.66207826700001),
 (41.783108678000005, -87.727773468),
 (41.731921596999996, -87.61527886799999),
 (41.758092329, -87.633682992),
 (41.95994957, -87.719222964),
 (41.721918366, -87.585137009),
 (41.773175037, -87.694462428),
 (41.759089096, -87.636941506),
 (41.700787634, -87.63900269700001),
 (41.903194786, -87.752155661),
 (41.85628526, -87.73255671),
 (41.843872347, -87.718440499),
 (41.945685321999996, -87.784841621),
 (41.808833439000004, -87.622824022),
 (41.871868682, -87.76189395899999),
 (41.768389276, -87.617698601),
 (41.925603879, -87.66816176),
 (41.765444001, -87.62690618100001),
 (41.93414043, -87.73485497600001),
 (41.953644262, -87.7281765),
 (41.953644262, -87.7281765),
 (41.782708931, -87.765571862),
 (41.782708931, -87.765571862),
 (41.729633491, -87.549855923),
 (41.671666189, -87.650234165),
 (41.759333905, -87.632071481),
 (41.885741529, -87.631344503),
 (41.872873835, -87.696811792),
 (41.760126869000004, -87.686788563),
 (41.851074338000004, -87.706449961),
 (41.92578275, -87.767575594),
 (41.726228859, -87.63605461899999),
 (41.750640764, -87.67679483399999),
 (41.847266278, -87.705121819),
 (41.740128582, -87.593880712),
 (41.847534945, -87.713659818),
 (41.859032957, -87.71002844200001),
 (41.748494145, -87.63481330200001),
 (41.908795816, -87.73138863700001),
 (41.86479699, -87.645784928),
 (41.884433056, -87.65239764200001),
 (41.87528403, -87.72427510799999),
 (41.894591453000004, -87.719944973),
 (41.750320089, -87.66638306899999),
 (41.830530933, -87.610277459),
 (41.756430631, -87.561470724),
 (41.948531468, -87.747156367),
 (41.875178061, -87.627619404),
 (41.759656906, -87.574916355),
 (41.757649901, -87.62152333899999),
 (41.789640031, -87.781703874),
 (41.720675898, -87.57270457899999),
 (41.764923919, -87.59824759799999),
 (41.862462006, -87.639458978),
 (41.906276004, -87.670011875),
 (42.018498254, -87.672983233),
 (41.74775752, -87.65245137),
 (41.98287878, -87.791440835),
 (41.979457791, -87.79927413899999),
 (41.876278295, -87.688732935),
 (41.905528856, -87.710557226),
 (41.746053316, -87.549146964),
 (41.906503477, -87.63931657299999),
 (41.761077973, -87.63455955299999),
 (41.736813463000004, -87.64972011799999),
 (41.891045813000005, -87.617950803),
 (41.888189539, -87.623777956),
 (41.751344208, -87.599820806),
 (41.903466617, -87.628667138),
 (41.859255273, -87.659962562),
 (41.671848709, -87.63088793700001),
 (41.92510186, -87.67199230700001),
 (41.766114415, -87.57203980799999),
 (41.744056769000004, -87.66813714700001),
 (41.76870453, -87.614128347),
 (41.987833463, -87.65814575),
 (41.923258751, -87.70340683399999),
 (41.738583501, -87.65341299299999),
 (41.857729000999996, -87.635971485),
 (41.949381495, -87.702998991),
 (41.768003513000004, -87.663875893),
 (41.730433934000004, -87.63981191100001),
 (41.844396937, -87.71392498200001),
 (41.743047782, -87.664985296),
 (41.738577072, -87.551450986),
 (41.716163105999996, -87.573362144),
 (41.757209187, -87.563392885),
 (41.754126154, -87.597982339),
 (41.750562355, -87.60764283),
 (41.793415261, -87.651212934),
 (41.844074266999996, -87.62844208799999),
 (41.809318774, -87.620544473),
 (41.753272058, -87.648962792),
 (41.761949861, -87.680616146),
 (41.87105086, -87.69716399100001),
 (41.703201242, -87.63786348100001),
 (41.895420644, -87.720539406),
 (41.857960294, -87.709080773),
 (41.906493907, -87.64000364),
 (41.876196845, -87.724082848),
 (41.753353571, -87.58164592899999),
 (41.897949791, -87.728625471),
 (41.767847633, -87.566498814),
 (41.72275081, -87.628692734),
 (41.977269698, -87.674442766),
 (41.917638549, -87.683702024),
 (41.903168813, -87.678492886),
 (41.861957634, -87.729937546),
 (41.94955828, -87.647198103),
 (41.947552818000005, -87.779991715),
 (41.889203579000004, -87.631600408),
 (41.804884238, -87.611350804),
 (41.94670237, -87.656117076),
 (41.993703698000004, -87.79415213200001),
 (41.964618881, -87.656975296),
 (41.780145444, -87.688549029),
 (41.78000107, -87.694636659),
 (41.947653829000004, -87.672465051),
 (41.772399326, -87.649800635),
 (41.886367084, -87.756509491),
 (41.89116528, -87.64926676600001),
 (41.897716039, -87.678015997),
 (41.8030864, -87.61173408799999),
 (41.738718395999996, -87.586726409),
 (41.7335097, -87.560576484),
 (41.79136464, -87.669371759),
 (41.96137851, -87.65474101),
 (41.986460964, -87.655283903),
 (41.845389113, -87.71115549),
 (41.849155068, -87.696782718),
 (41.813558308000005, -87.669960623),
 (41.684151193000005, -87.655501989),
 (41.989348532, -87.658192271),
 (41.953734204, -87.721845027),
 (41.883580684, -87.709595279),
 (41.911161199, -87.633564277),
 (41.879266261, -87.743794623),
 (41.87728542, -87.71010814600001),
 (41.908468358, -87.67664595299999),
 (41.804772841, -87.633256046),
 (41.978052908, -87.692576858),
 (41.693909486, -87.618275829),
 (41.876172139, -87.72615401700001),
 (41.841408158, -87.725690088),
 (42.021531238, -87.670717958),
 (41.911161199, -87.633564277),
 (41.877532811, -87.672387519),
 (41.952153269, -87.83223164799999),
 (41.877816835, -87.624307643),
 (41.883222953, -87.62563599299999),
 (41.859471978, -87.653426071),
 (41.885701678000004, -87.64379073200001),
 (41.855906241999996, -87.727274434),
 (41.896685065999996, -87.627683859),
 (41.739516056999996, -87.589120794),
 (41.805851501999996, -87.672189491),
 (41.871799513, -87.63293634700001),
 (41.756115887, -87.605326291),
 (41.794949113, -87.65488589799999),
 (41.738330132, -87.55631243399999),
 (41.851178006, -87.70033399799999),
 (42.009440899, -87.69601138200001),
 (41.87799992, -87.64309874899999),
 (41.765188879, -87.581936662),
 (41.952739718000004, -87.726295457),
 (41.88311784, -87.649044143),
 (41.784770393, -87.796500235),
 (41.673715251, -87.63455359700001),
 (41.753165736, -87.674434596),
 (41.784747667, -87.61896870700001),
 (41.817639449, -87.621435374),
 (41.94325465, -87.75752244600001),
 (41.88392995, -87.680114234),
 (41.82906505, -87.626519016),
 (41.715883887, -87.645803076),
 (41.926615689, -87.774594385),
 (41.933184269, -87.759898971),
 (41.97045428, -87.65625165799999),
 (41.88447178, -87.743732081),
 (41.772896632, -87.685908815),
 (41.791655285, -87.70644986100001),
 (41.807755932, -87.732628871),
 (41.768802381, -87.733476291),
 (41.877452438, -87.69455585),
 (41.984142866, -87.816823535),
 (41.941111746, -87.75431455299999),
 (41.786259089, -87.64860108399999),
 (41.760277756, -87.684345991),
 (41.786960419, -87.73644948),

In [29]:
stations_array = [(41.8583725929, -87.627356171), (41.8018110912, -87.6305601801), 
                  (41.7664308925, -87.6057478606), (41.7079332906, -87.5683491228),
                  (41.6927233639, -87.6045058667),
                 (41.7521368378, -87.6442289066), (41.7796315359, -87.6608870173),
                  (41.778987189, -87.7088638153),(41.8373944311, -87.6464077068),
                  (41.8566845327, -87.708381958),(41.8735822883, -87.705488126),
                  (41.8629766244, -87.6569725149),(41.9211033246, -87.6974518223),
                  (41.8800834614, -87.768199889),(41.9740944511, -87.7661488432),
                  (41.9660534171, -87.728114561),(41.9032416531, -87.6433521393),
                  (41.9474004564, -87.651512018),(41.9795495131, -87.6928445094),
                  (41.6914347795, -87.6685203937), (41.9997634842, -87.6713242922),
                  (41.9186088912, -87.765574479)]

In [30]:
station_array = np.array(stations_array)

In [31]:
chicago['Location'] = chicago_latitude_long_list

C:\Users\bsnus\.conda\envs\Decision Tree\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

## Formula to calculate distance of closest police station

In [32]:
%time
from timeit import Timer
import itertools
from math import radians, sin, cos, asin, sqrt, pi, atan2

distance = []
earth_radius_miles = 3958.8

x = chicago['Location']
y = station_array

def shortest(needle, haystack):
    dlat = np.radians(haystack[:, 0]) - radians(needle[0])
    dlong = np.radians(haystack[:, 1]) - radians(needle[1])
    a = np.square(np.sin(dlat/2)) + cos(radians(needle[0])) * np.cos(np.radians(haystack[:,0])) * np.square(np.sin(dlong/2))
    
    circle_distance = 2 * np.arcsin(np.minimum(np.sqrt(a), np.repeat(1, len(a))))
    d = earth_radius_miles * circle_distance
    return np.min(d)

Wall time: 0 ns

In [33]:
def donumpy():
    shortest(x, y)

In [34]:
for i in x:
    distance.append(shortest(i, y))

In [35]:
chicago['Closest Station'] = distance
chicago.head(10)

C:\Users\bsnus\.conda\envs\Decision Tree\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,ID,Date,Block,IUCR,Description,Location Description,Ward,Community Area,FBI Code,X Coordinate,...,Timeblock_6,Timeblock_9,Weekday_Friday,Weekday_Monday,Weekday_Saturday,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,Closest Station
62200,11626027,03/16/2019 05:58:00 PM,001XX N WELLS ST,0460,SIMPLE,STREET,42.0,32.0,08B,1174723.0,...,0,0,0,0,1,0,0,0,0,1.457263
62540,11622422,03/12/2019 10:00:00 PM,008XX E 38TH PL,0820,$500 AND UNDER,RESIDENTIAL YARD (FRONT/BACK),4.0,36.0,06,1182276.0,...,0,0,0,0,0,0,0,1,0,2.035700
62572,11625922,03/14/2019 06:42:00 PM,074XX N PAULINA ST,0460,SIMPLE,RESIDENCE,49.0,1.0,08B,1163827.0,...,0,0,0,0,0,0,1,0,0,1.160838
62646,11626065,03/16/2019 03:16:00 PM,069XX W FARRAGUT AVE,0486,DOMESTIC BATTERY SIMPLE,RESIDENCE,41.0,10.0,08B,1129134.0,...,0,0,0,0,1,0,0,0,0,1.771637
63098,11647322,04/07/2019 04:08:00 AM,001XX W CONGRESS PKWY,051A,AGGRAVATED: HANDGUN,STREET,25.0,32.0,04A,1174840.0,...,0,0,0,0,0,1,0,0,0,1.231120
63271,11661997,04/17/2019 03:45:00 PM,034XX W ARMITAGE AVE,0820,$500 AND UNDER,PARKING LOT/GARAGE(NON.RESID.),26.0,22.0,06,1153253.0,...,0,0,0,0,0,0,0,0,1,0.810186
63304,11662440,04/18/2019 07:30:00 PM,026XX W FULLERTON AVE,0820,$500 AND UNDER,STREET,1.0,22.0,06,1158218.0,...,0,0,0,0,0,0,1,0,0,0.311611
63368,11662357,04/20/2019 08:50:00 PM,076XX S EXCHANGE AVE,1506,SOLICIT ON PUBLIC WAY,STREET,7.0,43.0,16,1195776.0,...,0,0,0,0,1,0,0,0,0,2.541618
63369,11667968,04/19/2019 01:57:00 PM,002XX N LARAMIE AVE,1752,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,28.0,25.0,17,1141669.0,...,0,0,1,0,0,0,0,0,0,0.744495
63386,11664842,04/21/2019 10:22:00 PM,014XX S CANAL ST,0460,SIMPLE,OTHER,11.0,28.0,08B,1173362.0,...,0,0,0,0,0,1,0,0,0,0.659562

In [36]:
chicago.shape

(2547431, 84)

In [37]:
#Importing Dataset that has socio-economic data
hardship = pd.read_csv('hardship_index.csv')

In [38]:
hardship.head(10)

,HARDSHIP INDEX,COMMUNITY AREA NAME,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME
0,39.0,Rogers Park,23.6,18.2,8.7,27.5,23939
1,46.0,West Ridge,17.2,20.8,8.8,38.5,23040
2,20.0,Uptown,24.0,11.8,8.9,22.2,35787
3,17.0,Lincoln Square,10.9,13.4,8.2,25.5,37524
4,6.0,North Center,7.5,4.5,5.2,26.2,57123
5,5.0,Lake View,11.4,2.6,4.7,17.0,60058
6,2.0,Lincoln Park,12.3,3.6,5.1,21.5,71551
7,1.0,Near North Side,12.9,2.5,7.0,22.6,88669
8,8.0,Edison Park,3.3,7.4,6.5,35.3,40959
9,21.0,Norwood Park,5.4,11.5,9.0,39.5,32875

In [39]:
#Adding the per capita income column to the dataset
chicago['Income'] = chicago['Community Area'].apply(lambda row: hardship.iloc[int(row)-1].iloc[5])

C:\Users\bsnus\.conda\envs\Decision Tree\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [40]:
chicago['Income'] = chicago['Income']*1000

C:\Users\bsnus\.conda\envs\Decision Tree\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [41]:
chicago['HARDSHIP INDEX'] = chicago['Community Area'].apply(lambda row: hardship.iloc[int(row)-1].iloc[0])
chicago['Under18_over64'] = chicago['Community Area'].apply(lambda row: hardship.iloc[int(row)-1].iloc[5])
chicago['Unemployed'] = chicago['Community Area'].apply(lambda row: hardship.iloc[int(row)-1].iloc[4])
chicago['House_below_poverty'] = chicago['Community Area'].apply(lambda row: hardship.iloc[int(row)-1].iloc[2])

C:\Users\bsnus\.conda\envs\Decision Tree\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\bsnus\.conda\envs\Decision Tree\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\bsnus\.conda\envs\Decision Tree\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\bsnus\.conda\envs\Decision Tree\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [42]:
chicago.head()

,ID,Date,Block,IUCR,Description,Location Description,Ward,Community Area,FBI Code,X Coordinate,...,Weekday_Sunday,Weekday_Thursday,Weekday_Tuesday,Weekday_Wednesday,Closest Station,Income,HARDSHIP INDEX,Under18_over64,Unemployed,House_below_poverty
62200,11626027,03/16/2019 05:58:00 PM,001XX N WELLS ST,0460,SIMPLE,STREET,42.0,32.0,08B,1174723.0,...,0,0,0,0,1.457263,13500.0,3.0,13.5,5.7,14.7
62540,11622422,03/12/2019 10:00:00 PM,008XX E 38TH PL,0820,$500 AND UNDER,RESIDENTIAL YARD (FRONT/BACK),4.0,36.0,06,1182276.0,...,0,0,1,0,2.035700,40400.0,78.0,40.4,28.7,39.7
62572,11625922,03/14/2019 06:42:00 PM,074XX N PAULINA ST,0460,SIMPLE,RESIDENCE,49.0,1.0,08B,1163827.0,...,0,1,0,0,1.160838,27500.0,39.0,27.5,8.7,23.6
62646,11626065,03/16/2019 03:16:00 PM,069XX W FARRAGUT AVE,0486,DOMESTIC BATTERY SIMPLE,RESIDENCE,41.0,10.0,08B,1129134.0,...,0,0,0,0,1.771637,39500.0,21.0,39.5,9.0,5.4
63098,11647322,04/07/2019 04:08:00 AM,001XX W CONGRESS PKWY,051A,AGGRAVATED: HANDGUN,STREET,25.0,32.0,04A,1174840.0,...,1,0,0,0,1.231120,13500.0,3.0,13.5,5.7,14.7

In [43]:
#Importing for Exploratory Data Analysis 
chicago.to_csv('Chicago Data Cleanedup.csv')